import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import ComingSoon from '../components/comingSoon'
import ComingModal from '../components/ComingSoon/ComingModal'


export default function Home() {
  const [open, setOpen] = useState(true)

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {/* <ComingSoon /> */}
        <ComingModal open={open} setOpen={setOpen} />
        
       
</div>
      
    </div>
  )
}
